### ISSUE TITLE
Automatically re-start failed downloads

### ISSUE THREAD

**Issue by piranna** [piranna/download-manager#5]
When download fails due to disconnection, re-try to do the download. Since we don't cache the downloaded data and we directly de-compress it we can't be able to continue the download where it was left, but I think this is a minor problem.

So far I have found the next error related to disconnections thown by the `pump()` callback, probably there would be others that we need to listen for (`bzip2` files?) but this is a good starting point:

```Javascript
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
```

**Comment by piranna** [comment]
Full error trace:

```javascript
Trace: { Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
    at /home/piranna/Proyectos/nodeos-cross-toolchain/scripts/prebuild:174:13
    at /home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/download-manager/index.js:280:11
    at /home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/async/dist/async.js:997:17)
    at /home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/async/dist/async.js:847:20
    at /home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/download-manager/index.js:233:9
    at /home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/async/dist/async.js:486:20
    at replenish (/home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/async/dist/async.js:879:29)
    at iterateeCallback (/home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/async/dist/async.js:869:21)
    at /home/piranna/Proyectos/nodeos-cross-toolchain/node_modules/async/dist/async.js:847:20
```
